### ISSUE TITLE
豆瓣的开发者平台，现在个人不能使用了；还可以提供数据的接口有https://api.douban.com/v2/book/1220563，但是貌似没有isbn的参数，有没有解决方案呢？

### ISSUE THREAD

**Issue by JeffcottLu** [Littlesqx/douban-book#12]

**Comment by Littlesqx** [comment]
你好，谢谢反馈。刚刚测试，https://api.douban.com/v2/book/isbn/9787543632349 是还能用的，试试看？

**Comment by JeffcottLu** [comment]
嗯，刚刚没看清，以为是接口的问题；应该是\Littlesqx\Book\BookFactory::make里setAltUrl这里$params这个变量没有alt_url这个元素的问题；

**Comment by JeffcottLu** [comment]
![image](https://user-images.githubusercontent.com/8591495/52915196-d607c100-330b-11e9-9788-0a23c30bc8c6.png)

用的也是readme里提供的9787115473899这个isbn号；

**Comment by Littlesqx** [comment]
@JeffcottLu 更新一下包，不知道是对方更改字段名还是我之前写错了，用 1.0.3 版本
